<a href="https://colab.research.google.com/github/annabohrer/Data-Science/blob/main/Anna_Bohrer_Stats_2023_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

### Loops

In [73]:
for i in range(100):                                                            #printing 100 numbers starting at 0
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [74]:
for i in range(5,8):                                                            #printing numbers between 5 and 8 but nit including 8
    print(i)

5
6
7


In [75]:
for i in range(3):                                                              #printing 3 numbers
    print( "Test Number: " , i )                                                #add this word in front of the numbers

Test Number:  0
Test Number:  1
Test Number:  2


### Functions

In [76]:
def square(x):                                                                  #defining the phrase to equal the equation
    return x**2                                                                 #the equation is to square the x which is in the phrase

In [77]:
square(5)                                                                       #inputing 5 as x

25

In [78]:
square(square(2))                                                               #using the phrase twice and with the number 2
                                                                                #squaring the squared number of 2

16

In [79]:
square(square(square(2)))                                                       #using the phrase three times and with the number 2


256

In [80]:
square(123456)                                                                  #squaring a large number

15241383936

In [81]:
square(square(5))                                                               #squaring the squared number of 5

625

In [82]:
def add_two(x):                                                                 #defining the phrase add two to equal the equation
    return x+2                                                                  #adding 2 to what ever x will be 

In [83]:
add_two(5)                                                                      #x is given as 5 so it adds 2

7

In [84]:
square(add_two(5))                                                              #using both phrases
                                                                                #adding 2 to 5 and then square it

49

### Logical Branching

In [85]:
choice = "apple"                                                                #defining choice

In [86]:
if choice == "apple":

    print("You choose apples.")                                                 #if you chose apples this gets printed

else:
    
    print("You did not choose apples.")                                         #if you choose anything else this is printed

You choose apples.


In [87]:
choice = "orange"                                                               #picked orange as the choice

In [88]:
if choice == "apple":                                                           #same as before but the choice is orange

    print("You choose apples.")

else:                                                                           #since it is orange this will be printed
    
    print("You did not choose apples.")

You did not choose apples.


In [89]:
choice = "apple"                                                                #the choice is apple so it will print what is defined below

In [90]:
if choice == "apple":                                                           #when you choose apple the three lines will be printed

    print("You choose apples.")
    print("Thank you, shop again!")
    print(2**123)

elif choice == "orange":                                                        #orange is the other option

    print("You choose oranges.")
    print("Thank you, shop again!")

else:                                                                           #if you don't choose either this will be printed
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


### User Input

In [91]:
choice = input("Please enter your choice (i.e. apple): ")                       #it will ask you what your choice will be and will continue to run until you input a choice

Please enter your choice (i.e. apple): apple


In [92]:
choice                                                                          #it will come up with your choice

'apple'

In [93]:
if choice == "apple":                                                           #if you choose apple this will be printed

    print("You choose apples.")

elif choice == "oranges":                                                       #oranges is the other choice

    print("You choose oranges.")

else:                                                                           #anything else this will be printed  
    
    print("You did not choose apples or oranges.")

You choose apples.


#### Coins

In [94]:
import numpy as np                                                              #import numpy so you can run all the rest


In [95]:
np.random.random()                                                              #will come up with a random number

0.6504746254769022

In [96]:
np.random.random() > 0.5                                                        #if the random number is greater than 0.5 it will be true vs. not and will be false

True

In [97]:
def flip_coin():
    if np.random.random() > 0.5:                                                #if the random number is true it will be heads
        print("Heads")
    else:                                                                       #any other number will be tails
        print("Tails")

In [98]:
flip_coin()                                                                     #it is different each time its run

Tails


### Graphics Output

In [99]:
from IPython.core.display import display, HTML                                  #importing this so we can import pictures with just the HTML

In [100]:
display(HTML('<h1>Hello, world!</h1>'))                                         #making a heading

In [101]:
def coin():                                                                     #defining coin to equal 2 numbers either 1 or 0
  return np.random.randint(2)

In [102]:
coin()                                                                          #it will show either a 0 or a 1

0

In [103]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">'))       #importing an image

In [104]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg'      #heads will be this photo
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg'       #tails will be this one

In [105]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))                                        #using this phrase and the word that equals the picture

In [106]:
show_img(heads)                                                                 #will produce the photo that equals heads

In [107]:
show_img(tails)                                                                 #produces the tails picture

In [108]:
def flip_coin():                                                                #flip coin is made in the above code and will produce the word heads or tails

    if coin():                                                                  #if its comes out as heads it will show this image. anything greater than 0.5
        show_img(heads)
    else:                                                                       #anything else will show the tails
        show_img(tails)

In [109]:
flip_coin()                                                                     #randomized coin flip based on the code above and different each time

In [110]:
for i in range(5):
    flip_coin()                                                                 #flipping the coin 5 times

In [111]:
#@title Coin Flip

if coin():

  show_img(heads)

else:

  show_img(tails)

### Cards

In [112]:
def shuffle(x):                                                                 #defining what shuffle means
    for i in range(len(x)-1,0,-1):
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

In [113]:
a = np.arange(52)                                                               #array of 52 numbers 0-52

In [114]:
shuffle(a)                                                                      #shuffle the array of the 52 numbers

array([39,  7, 43, 19, 26,  1, 22, 47, 45, 31,  6, 11, 29, 23, 33, 36,  9,
       35, 37,  4, 27, 42, 12, 14, 49,  5, 50,  8, 15, 48, 28, 20, 44, 34,
        2, 25,  3, 38, 46, 13, 32, 18, 30,  0, 51, 16, 21, 40, 41, 24, 17,
       10])

In [115]:
np.random.permutation(52)                                                       #random order of the numbers

array([37, 20, 14, 41,  3, 39, 19, 24, 45, 18, 38, 44, 35, 11, 36, 23, 30,
       51,  6, 29, 10, 48, 34, 47, 31,  2,  0, 25,  7, 26, 15, 27,  4, 22,
       21, 32,  9, 42, 12, 16, 28, 50,  8, 43, 13, 46, 49,  5,  1, 33, 40,
       17])

### Speed Test

In [116]:
%%timeit
shuffle(a)                                                                      #how fast it shuffles the numbers

171 µs ± 8.67 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [117]:
%%timeit
np.random.permutation(52)                                                       #how fast the numbers are arranged

3.55 µs ± 165 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [118]:
import numpy as np                                                              #importing an outside thing

In [119]:
np.random.permutation(52)                                                       #randomized numbers from 0-51

array([25, 50, 45, 38,  2,  7, 12, 27, 49, 15, 28, 32,  6,  5, 17, 24, 21,
       31,  0,  1,  3,  8, 19, 10, 22, 23, 51, 40, 26, 46,  9, 13, 14, 35,
       34,  4, 41, 30, 44, 33, 36, 47, 16, 48, 11, 20, 39, 42, 29, 43, 18,
       37])

In [120]:
cards = np.random.permutation(52)                                               #defining cards as a random order

In [121]:
cards                                                                           #seeing what cards will be

array([40,  9, 14, 43, 23, 25, 29,  6, 18, 45,  8, 38, 31, 46, 21, 37, 17,
        5, 16, 30,  7, 41, 10,  4,  3, 24, 35, 42, 12, 50, 19, 36,  2,  1,
       27, 15, 13, 34, 20, 32, 48, 47, 22, 11, 39, 51, 26,  0, 44, 28, 49,
       33])

In [122]:
cards[0]                                                                        #what number is in the 0 spot

40

In [123]:
cards[1]                                                                        #the number 17 is in the same spot as the number 1 would be

9

In [124]:
cards[2]                                                                        #in the place of the number 2 the number 28 is there

14

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [125]:
np.arange(52).reshape(4,13)                                                     #arranging 52 numbers into 4 rows and 13 columns

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [126]:
np.arange(52).reshape(4,13)%13                                                  #first 13 numbers of the arrangement repeated in 4 rows

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [127]:
np.arange(52).reshape(4,13)//13                                                 #first 4 numbers repeated in each of the 13 columns

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [128]:
suits = ['Clubs','Spades','Hearts','Diamonds']                                                          #defining the suits names
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']    #defining the names of the cards

In [129]:
def card_name(card_number):                                                     #using the card name and the card number
    
    suit = card_number//13                                                      #the suit will only be chosen from 4 numbers as shown above
    name = card_number%13                                                       #the name will be chosen from only 13 numbers

    return names[name] + " of " + suits[suit]                                   #it will come up with the name and the word of and the name of the suit

In [130]:
card_name(0)                                                                    #showing that 0 will be this card

'Ace of Clubs'

In [131]:
card_name(51)                                                                   #the last will be this

'King of Diamonds'

In [132]:
cards = np.random.permutation(52)                                               #cards defined as a random order of 52 numbers

In [133]:
top_of_deck         = card_name(cards[0])                                       #card name is shown above and the cards are based off the arrangement further above
second_card_in_deck = card_name(cards[1])                                       #second card is the same like the top card
last_card_in_deck   = card_name(cards[-1])                                      #same

In [134]:
top_of_deck, second_card_in_deck, last_card_in_deck                             #shows how the cards will be made

('Six of Clubs', 'King of Diamonds', 'Five of Spades')

In [135]:
for i in range(5):                                                              #printing 5 cards
    print(card_name(cards[i]))                                                  #will print the card name and the order 

Six of Clubs
King of Diamonds
Six of Hearts
Two of Clubs
Five of Hearts


In [136]:
for i in range(15):                                                             #printing 15 cards
    print(card_name(cards[i]))                                                  #the same first 5 cards as before and then the rest of it

Six of Clubs
King of Diamonds
Six of Hearts
Two of Clubs
Five of Hearts
Four of Spades
Jack of Hearts
Four of Clubs
Queen of Spades
Seven of Spades
Ten of Diamonds
Queen of Diamonds
Six of Diamonds
Seven of Hearts
King of Clubs


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [137]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"      #photo of the face of the card
card_url_tail = ".png"                                                          #photo of the back of the card

In [138]:
suit = ['k','p','s','l']                                                        #the four suits defined as suit
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']                   #the card numbers

In [139]:
i = np.random.randint(4)                                                        #random
j = np.random.randint(13)

In [140]:
i,j                                                                             #two numbers from the two letters

(2, 12)

In [141]:
suit[i]                                                                         #random suit based off i

's'

In [142]:
card[j]                                                                         #random card based off j

'k'

In [143]:
from IPython.core.display import display, HTML                                  #using this to import photos with the HTML

In [144]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))                                        #defining show img to show the image

In [145]:
img = card_url_head + suit[i] + card[j] + card_url_tail                         #the image is of the face card with the suit and card number stated and then the back of the card too

In [146]:
show_img(img)                                                                   #showing the image

In [147]:
def card_image(card_number):                                                    #defining the image with the card number
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]                                                      #show the suit and the number

In [148]:
card_image(3)                                                                   #the third card will be

'k4'

In [149]:
img = card_url_head + card_image(3) + card_url_tail                             #definning the image of the 3rd card

In [150]:
show_img(img)                                                                   #showing the image

In [151]:
for i in range(52):                                                             #showing the images of 52 cards
    img = card_url_head + card_image(i) + card_url_tail                         #what the images are
    show_img(img)                                                               #it will show these images